#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""
embed_firmware.py — fetch the Realtek RTL8761BU Bluetooth firmware from
linux-firmware (if not already present) and generate RTLFirmwareData.hpp so the
blobs are compiled directly into the kext.

The firmware is NOT redistributed in this repo (Realtek's license); it is
downloaded at build time from kernel.org. Run automatically by `make`.
"""

import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "RTLFirmwareData.hpp"
RES = HERE / "Resources"
FW_BU = RES / "rtl8761bu_fw.bin"
CFG_BU = RES / "rtl8761bu_config.bin"
FW_B = RES / "rtl8761b_fw.bin"
CFG_B = RES / "rtl8761b_config.bin"

BASE = ("https://git.kernel.org/pub/scm/linux/kernel/git/firmware/"
        "linux-firmware.git/plain/rtl_bt/")


def fetch(path: Path) -> None:
    """Download a firmware file from linux-firmware if it isn't already here."""
    if path.exists() and path.stat().st_size > 0:
        return
    url = BASE + path.name
    print(f"  downloading {path.name} from linux-firmware…")
    RES.mkdir(exist_ok=True)
    try:
        import subprocess
        subprocess.run(["curl", "-s", "-f", "-L", "-o", str(path), url], check=True)
        data = path.read_bytes()
    except Exception as e:  # noqa: BLE001
        sys.exit(f"ERROR: could not download {url}\n  {e}\n"
                 f"  Download it manually to {path} and re-run.")
    if not data:
        sys.exit(f"ERROR: downloaded {path.name} is empty.")
    path.write_bytes(data)
    print(f"    saved {len(data)} bytes")


def c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    return (
        f"static const uint8_t {name}[] = {{\n{body}\n}};\n"
        f"static const uint32_t {name}Len = {len(data)};\n"
    )


def main() -> None:
    fetch(FW_BU)
    fetch(CFG_BU)
    fetch(FW_B)
    fetch(CFG_B)

    fw_bu = FW_BU.read_bytes()
    cfg_bu = CFG_BU.read_bytes()
    fw_b = FW_B.read_bytes()
    cfg_b = CFG_B.read_bytes()

    if fw_bu[:8] != b"Realtech" or fw_b[:8] != b"Realtech":
        sys.exit("ERROR: missing 'Realtech' epatch signature — corrupt download?")
    if cfg_bu[:4] != bytes([0x55, 0xAB, 0x23, 0x87]) or cfg_b[:4] != bytes([0x55, 0xAB, 0x23, 0x87]):
        sys.exit("ERROR: missing Realtek config signature — corrupt download?")

    OUT.write_text(
        "// RTLFirmwareData.hpp — GENERATED by embed_firmware.py. Do not edit.\n"
        "// Firmware: linux-firmware rtl_bt/rtl8761bu_fw.bin + rtl8761bu_config.bin\n"
        "// Firmware: linux-firmware rtl_bt/rtl8761b_fw.bin + rtl8761b_config.bin\n"
        "#pragma once\n\n"
        + c_array("kRtl8761buFw", fw_bu)
        + "\n"
        + c_array("kRtl8761buConfig", cfg_bu)
        + "\n"
        + c_array("kRtl8761bFw", fw_b)
        + "\n"
        + c_array("kRtl8761bConfig", cfg_b),
        encoding="utf-8",
    )
    print(f"Generated {OUT.name}: BU fw={len(fw_bu)}, BU config={len(cfg_bu)}, B fw={len(fw_b)}, B config={len(cfg_b)}")


if __name__ == "__main__":
    main()
