// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * RTLBluetoothFirmware.cpp
 *
 * IOKit kext — uploads Realtek RTL8761BU firmware to the TP-Link UB500
 * Bluetooth dongle so the macOS 12+ userspace Bluetooth stack (bluetoothd,
 * patched by BlueToolFixup) can drive it as a standard HCI controller.
 *
 * Protocol derived from Linux drivers/bluetooth/btrtl.c + btusb.c.
 */

#include "RTLBluetoothFirmware.hpp"
#include <IOKit/pwr_mgt/IOPM.h>
#include <IOKit/usb/IOUSBHostFamily.h>
#include "RTLFirmwareData.hpp"      // generated by embed_firmware.py
#include <kern/clock.h>
#include <pexpert/pexpert.h>

#define super IOService
OSDefineMetaClassAndStructors(RTLBluetoothFirmware, IOService)

// ─────────────────────────────────────────────────────────────────────────────
// Lifecycle
// ─────────────────────────────────────────────────────────────────────────────

bool RTLBluetoothFirmware::start(IOService *provider)
{
    IOLog(DRV ": start — TP-Link UB500 (RTL8761BU) firmware loader v1.3\n");

    {
        char dummy[8] = {};
        m_wakeSafe = PE_parse_boot_argn("-rtlwakesafe", dummy, sizeof(dummy));
    }

    if (!super::start(provider)) {
        IOLog(DRV ": super::start failed\n");
        return false;
    }

    m_workLoop = IOWorkLoop::workLoop();
    if (!m_workLoop) {
        IOLog(DRV ": failed to create work loop\n");
        super::stop(provider);
        return false;
    }

    m_pmTimer = IOTimerEventSource::timerEventSource(this, pmTimerCallback);
    if (m_pmTimer) {
        if (m_workLoop->addEventSource(m_pmTimer) != kIOReturnSuccess) {
            OSSafeReleaseNULL(m_pmTimer);
        }
    }

    PMinit();
    provider->joinPMtree(this);
    m_powerState = 1; // Prevent handleWake on initial register
    static IOPMPowerState sPowerStates[2] = {
        {1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {1, kIOPMPowerOn, kIOPMPowerOn, kIOPMPowerOn, 0, 0, 0, 0, 0, 0, 0, 0}
    };
    registerPowerDriver(this, sPowerStates, 2);

    // NOTE: no rename here. Naming the device "Bluetooth USB Host Controller"
    // makes bluetoothd treat it as Apple's *internal* Broadcom controller and
    // send Broadcom-only vendor commands (fails with STATUS 718).

    IOReturn ret = openUSB(provider);
    if (ret == kIOReturnSuccess) {
        ret = runFirmwareUpload();
    }
    closeUSB();

    if (ret != kIOReturnSuccess) {
        IOLog(DRV ": firmware upload FAILED: 0x%08X\n", ret);
        setProperty("RTL-Status", "FAILED");
        setProperty("RTL-error", (unsigned long long)ret, 32);
        provider->setProperty("RTL-error", (unsigned long long)ret, 32);
        // We do not stop() here: stay in PM and retry shortly (and on wake).
        scheduleRetry();
    } else {
        /*
         * Success: all USB handles are closed, so userspace (bluetoothd /
         * BlueTool, patched by BlueToolFixup) is free to claim the device.
         * We stay attached as a passive registry entry in our own match
         * category — visible in ioreg for debugging, owning nothing.
         */
        if (!getProperty("RTL-Status"))
            setProperty("RTL-Status", "firmware uploaded");
        IOLog(DRV ": done — device released for the Bluetooth stack\n");
    }

    setProperty("RTL-wake_policy", m_wakeSafe ? "safe (-rtlwakesafe)" : "reload");
    registerService();
    return true;
}

void RTLBluetoothFirmware::stop(IOService *provider)
{
    if (m_pmTimer) {
        m_pmTimer->cancelTimeout();
        if (m_workLoop)
            m_workLoop->removeEventSource(m_pmTimer);
    }
    PMstop();
    closeUSB();
    super::stop(provider);
}

void RTLBluetoothFirmware::free()
{
    OSSafeReleaseNULL(m_pmTimer);
    OSSafeReleaseNULL(m_workLoop);
    closeUSB();
    super::free();
}

// ─────────────────────────────────────────────────────────────────────────────
// Power Management (Sleep/Wake)
// ─────────────────────────────────────────────────────────────────────────────

unsigned long RTLBluetoothFirmware::maxCapabilityForDomainState(IOPMPowerFlags domainState)
{
    return (domainState & kIOPMPowerOn) ? 1 : 0;
}

unsigned long RTLBluetoothFirmware::initialPowerStateForDomainState(IOPMPowerFlags domainState)
{
    return (domainState & kIOPMPowerOn) ? 1 : 0;
}

IOReturn RTLBluetoothFirmware::setPowerState(unsigned long powerStateOrdinal, IOService *whatDevice)
{
    if (powerStateOrdinal == 0) {
        // Going to sleep
        IOLog(DRV ": PM going to sleep (state 0)\n");
        m_powerState = 0;
        m_retryPending = false;          // wake handler takes over after sleep
        if (m_pmTimer)
            m_pmTimer->cancelTimeout();
    } else {
        // Waking up
        if (m_powerState != 1) {
            m_powerState = 1;
            IOLog(DRV ": PM waking up (state 1)\n");
            // Defer firmware upload to timer so we don't block the power thread
            if (m_pmTimer)
                m_pmTimer->setTimeoutMS(500);
        } else {
            IOLog(DRV ": PM already in state 1 (initial registration)\n");
        }
    }
    return IOPMAckImplied;
}

void RTLBluetoothFirmware::pmTimerCallback(OSObject *owner, IOTimerEventSource *sender)
{
    RTLBluetoothFirmware *self = OSDynamicCast(RTLBluetoothFirmware, owner);
    if (!self)
        return;
    if (self->m_retryPending)
        self->handleRetry();
    else
        self->handleWake();
}

// ─────────────────────────────────────────────────────────────────────────────
// Boot-time retry
//
// A failed upload at boot is usually a USB timing hiccup (the device is still
// settling, or another driver probed it first). Retry a few times with growing
// delays. bluetoothd starts ~15-20 s after this kext, so the retries normally
// run before it claims the device; if it already holds the HCI interface we
// back off instead of tearing its configuration down.
// ─────────────────────────────────────────────────────────────────────────────

static const uint32_t kRetryDelaysMs[] = { 2000, 5000, 10000 };
static const uint32_t kMaxRetries = sizeof(kRetryDelaysMs) / sizeof(kRetryDelaysMs[0]);

void RTLBluetoothFirmware::scheduleRetry()
{
    if (!m_pmTimer || m_retryCount >= kMaxRetries) {
        setProperty("RTL-retry", "giving up (no more retries)");
        m_retryPending = false;
        return;
    }
    uint32_t delay = kRetryDelaysMs[m_retryCount];
    m_retryPending = true;
    m_pmTimer->setTimeoutMS(delay);
    IOLog(DRV ": scheduling retry %u/%u in %u ms\n", m_retryCount + 1, kMaxRetries, delay);
}

void RTLBluetoothFirmware::handleRetry()
{
    m_retryPending = false;
    m_retryCount++;
    setProperty("RTL-retry_count", (unsigned long long)m_retryCount, 32);

    IOService *provider = getProvider();
    if (!provider)
        return;

    IOReturn ret = openUSB(provider);
    if (ret == kIOReturnSuccess)
        ret = runFirmwareUpload();
    closeUSB();

    if (ret == kIOReturnSuccess) {
        removeProperty("RTL-error");
        if (IOService *p = getProvider()) p->removeProperty("RTL-error");
        setProperty("RTL-retry", "succeeded");
        IOLog(DRV ": retry %u succeeded\n", m_retryCount);
    } else if (ret == kIOReturnExclusiveAccess) {
        // Someone (bluetoothd) owns the device now — do not fight it.
        setProperty("RTL-retry", "stopped: device in use by Bluetooth stack");
        IOLog(DRV ": retry %u: device in use, stopping\n", m_retryCount);
    } else {
        setProperty("RTL-Status", "FAILED");
        setProperty("RTL-error", (unsigned long long)ret, 32);
        IOLog(DRV ": retry %u failed: 0x%08X\n", m_retryCount, ret);
        scheduleRetry();
    }
}

void RTLBluetoothFirmware::handleWake()
{
    m_wakeCount++;
    setProperty("RTL-wake_count", (unsigned long long)m_wakeCount, 32);
    if (m_wakeSafe)
        wakeSafeCheck();
    else
        wakeReload();
}

/*
 * Default wake policy (same effect as the original 1.2 driver, made explicit).
 *
 * Reclaim the HCI interface from the Bluetooth stack (re-setting the USB
 * configuration if it is held), drop the patch with 0xFC66 and upload the
 * firmware again. bluetoothd sees the controller go away and come back and
 * re-initialises it from scratch, which is what this chip needs after sleep.
 */
void RTLBluetoothFirmware::wakeReload()
{
    IOLog(DRV ": wake — reloading firmware (fresh controller)\n");
    IOService *provider = getProvider();
    if (!provider) return;

    m_inWake       = false;
    m_forceReclaim = true;
    IOReturn ret = openUSB(provider);
    if (ret == kIOReturnSuccess)
        ret = runFirmwareUpload();
    closeUSB();
    m_forceReclaim = false;

    const char *result = (ret == kIOReturnSuccess) ? "reloaded" : "reload FAILED";
    setProperty("RTL-last_wake", result);
    if (ret != kIOReturnSuccess)
        setProperty("RTL-error", (unsigned long long)ret, 32);
    else
        removeProperty("RTL-error");
    IOLog(DRV ": wake result: %s (0x%08X)\n", result, ret);
}

/*
 * Experimental wake policy (-rtlwakesafe): only act if the chip is genuinely
 * back in ROM mode; never reconfigure, reset or re-upload a live controller.
 */
void RTLBluetoothFirmware::wakeSafeCheck()
{
    IOLog(DRV ": wake — checking whether firmware survived (safe mode)\n");
    IOService *provider = getProvider();
    if (!provider) return;

    m_inWake = true;

    const char *result;
    IOReturn ret = openUSB(provider);
    if (ret == kIOReturnExclusiveAccess) {
        result = "skipped: device in use by Bluetooth stack";
        ret = kIOReturnSuccess;
    } else if (ret == kIOReturnSuccess) {
        ret = runFirmwareUpload();
        OSString *st = OSDynamicCast(OSString, getProperty("RTL-Status"));
        result = (ret == kIOReturnSuccess)
                 ? (st ? st->getCStringNoCopy() : "ok")
                 : "re-upload FAILED";
    } else {
        result = "could not open device";
    }
    closeUSB();
    m_inWake = false;

    setProperty("RTL-last_wake", result);
    if (ret != kIOReturnSuccess)
        setProperty("RTL-error", (unsigned long long)ret, 32);
    IOLog(DRV ": wake result: %s (0x%08X)\n", result, ret);
}

bool RTLBluetoothFirmware::isRomMode(const RtlLocalVersion &v) const
{
    return v.lmpSubver == RTL8761BU_ROM_LMP_SUBVER &&
           v.hciRev    == RTL8761BU_ROM_HCI_REV   &&
           v.hciVer    == RTL8761BU_ROM_HCI_VER;
}

// ─────────────────────────────────────────────────────────────────────────────
// High-level firmware upload flow (mirrors btrtl_initialize + download)
// ─────────────────────────────────────────────────────────────────────────────

IOReturn RTLBluetoothFirmware::runFirmwareUpload()
{
    IOReturn        ret;
    RtlLocalVersion ver = {};

    auto repN = [this](const char *k, unsigned long long v) {
        setProperty(k, v, 32);
        if (IOService *p = getProvider()) p->setProperty(k, v, 32);
    };
    auto repS = [this](const char *k, const char *v) {
        setProperty(k, v);
        if (IOService *p = getProvider()) p->setProperty(k, v);
    };
    removeProperty("RTL-Status");
    repS("RTL-step", "read local version");

    ret = readLocalVersion(&ver);
    if (ret != kIOReturnSuccess) {
        IOLog(DRV ": HCI Read Local Version failed: 0x%08X\n", ret);
        repN("RTL-error", ret);
        return ret;
    }
    repN("RTL-hci_ver", ver.hciVer);
    repN("RTL-hci_rev", ver.hciRev);
    repN("RTL-lmp_subver", ver.lmpSubver);
    repS("RTL-step", "got local version");
    IOLog(DRV ": hci_ver=0x%02X hci_rev=0x%04X lmp_subver=0x%04X\n",
          ver.hciVer, ver.hciRev, ver.lmpSubver);

    /*
     * Warm reboot: the patch RAM survives, so the chip reports the firmware
     * version instead of the ROM identity. Like btrtl.c, send the vendor
     * "drop firmware" command (0xFC66, no completion event), wait, and
     * re-read until the chip is back in ROM mode.
     */
    if (!isRomMode(ver) && m_inWake) {
        // Patch survived sleep: the controller is live, leave it alone.
        repS("RTL-Status", "wake: firmware still active, nothing to do");
        return kIOReturnSuccess;
    }

    if (!isRomMode(ver)) {
        IOLog(DRV ": not in ROM mode — sending vendor reset (0xFC66)\n");
        repS("RTL-boot_path", "warm: chip was patched, vendor reset sent");
        hciCmd(RTL_OP_DROP_FW, nullptr, 0);
        IOSleep(300);

        bool back = false;
        for (int i = 0; i < 4 && !back; i++) {
            ret = readLocalVersion(&ver);
            if (ret == kIOReturnSuccess) {
                back = isRomMode(ver);
                if (back) break;
            }
            IOSleep(250);
        }

        if (!back) {
            // Chip refuses to drop to ROM — leave whatever firmware is
            // running untouched rather than risk a dead controller.
            if (ret == kIOReturnSuccess)
                IOLog(DRV ": chip did not return to ROM mode "
                      "(lmp_subver=0x%04X) — leaving device as-is\n",
                      ver.lmpSubver);
            else
                IOLog(DRV ": chip unresponsive after vendor reset "
                      "(0x%08X) — leaving device as-is\n", ret);
            repS("RTL-Status", "skipped (not in ROM mode)");
            repN("RTL-after_reset_lmp_subver", ver.lmpSubver);
            return kIOReturnSuccess;
        }
    }

    if (!getProperty("RTL-boot_path"))
        repS("RTL-boot_path", "cold: chip was in ROM mode");

    uint8_t romVersion = 0;
    ret = rtlReadRomVersion(&romVersion);
    if (ret != kIOReturnSuccess) {
        IOLog(DRV ": read ROM version failed: 0x%08X\n", ret);
        repN("RTL-error", ret);
        return ret;
    }
    repN("RTL-rom_version", romVersion);
    repS("RTL-step", "got rom version");
    IOLog(DRV ": rom_version=0x%02X (patch chip id %u)\n",
          romVersion, romVersion + 1);

    uint8_t  *image    = nullptr;
    uint32_t  imageLen = 0;
    ret = buildDownloadImage(romVersion, &image, &imageLen);
    if (ret != kIOReturnSuccess) {
        repN("RTL-error", ret);
        repS("RTL-step", "buildDownloadImage failed");
        return ret;
    }
    repN("RTL-image_len", imageLen);
    repS("RTL-step", "downloading");
    IOLog(DRV ": download image %u bytes\n", imageLen);

    ret = rtlDownload(image, imageLen);
    IOFree(image, imageLen);
    if (ret != kIOReturnSuccess) {
        repN("RTL-error", ret);
        repS("RTL-step", "rtlDownload failed");
        return ret;
    }
    repS("RTL-step", "download complete");

    // Like btrtl.c: read the version again to confirm the patch took.
    IOSleep(100);
    ret = readLocalVersion(&ver);
    if (ret == kIOReturnSuccess) {
        repN("RTL-post_hci_rev", ver.hciRev);
        repN("RTL-post_lmp_subver", ver.lmpSubver);
        repS("RTL-Status", isRomMode(ver) ? "download done but chip still reports ROM version"
                                          : "firmware uploaded, patch active");
        IOLog(DRV ": post-download fw version 0x%04X%04X\n",
              ver.hciRev, ver.lmpSubver);
        if (isRomMode(ver))
            IOLog(DRV ": WARNING — version unchanged, patch may not be active\n");
    } else {
        repN("RTL-post_read_err", ret);
        repS("RTL-Status", "download done, post-read failed");
        IOLog(DRV ": post-download version read failed: 0x%08X "
              "(fragments all ACKed, continuing)\n", ret);
    }

    return kIOReturnSuccess;
}

// ─────────────────────────────────────────────────────────────────────────────
// USB setup / teardown
// ─────────────────────────────────────────────────────────────────────────────

IOReturn RTLBluetoothFirmware::openUSB(IOService *provider)
{
    m_device = OSDynamicCast(IOUSBHostDevice, provider);
    if (!m_device) {
        IOLog(DRV ": provider is not IOUSBHostDevice\n");
        return kIOReturnBadArgument;
    }

    if (!m_device->open(this)) {
        IOLog(DRV ": could not open USB device\n");
        m_device = nullptr;
        return kIOReturnExclusiveAccess;
    }

    const StandardUSB::DeviceDescriptor *devDesc = m_device->getDeviceDescriptor();
    uint16_t idVendor = devDesc ? OSSwapLittleToHostInt16(devDesc->idVendor) : 0;
    uint16_t idProduct = devDesc ? OSSwapLittleToHostInt16(devDesc->idProduct) : 0;
    if ((idVendor == 0x2357 && idProduct == 0x0604) || (idVendor == 0x0bda && idProduct == 0xa728)) {
        m_chipVariant = ChipVariant::RTL8761BU;
        IOLog(DRV ": matched RTL8761BU firmware requirement (Vendor: 0x%04X, Product: 0x%04X)\n", idVendor, idProduct);
    } else {
        m_chipVariant = ChipVariant::RTL8761B;
        IOLog(DRV ": matched RTL8761B firmware requirement (Vendor: 0x%04X, Product: 0x%04X)\n", idVendor, idProduct);
    }

    /*
     * AppleUSBHostCompositeDevice only matches composite devices
     * (bDeviceClass 0x00/0xEF); the UB500 reports bDeviceClass 0xE0, so
     * nobody else will configure it — set configuration 1 ourselves as
     * soon as the first scan comes up empty, then wait for the
     * IOUSBHostInterface nubs to publish.
     */
    const int maxAttempts = m_inWake ? 4 : 24;
    m_ifaceBusy = false;
    for (int attempt = 0; attempt < maxAttempts && !m_interface; attempt++) {
        if (findHCIInterface())
            break;
        if (m_ifaceBusy && !m_forceReclaim) // held by the stack: back off (boot retry / safe wake)
            break;
        if (attempt == 0 && !m_inWake) {   // never tear down a live configuration on wake
            IOLog(DRV ": no interface nubs — setting configuration 1\n");
            IOReturn cfgRet = m_device->setConfiguration(1, true);
            if (cfgRet != kIOReturnSuccess)
                IOLog(DRV ": setConfiguration failed: 0x%08X\n", cfgRet);
        }
        IOSleep(250);
    }

    if (!m_interface) {
        IOLog(DRV ": HCI interface (class E0/01/01) not available\n");
        m_device->close(this);
        m_device = nullptr;
        // The interface exists but is held (normally by bluetoothd).
        if (m_forceReclaim)
            return kIOReturnNotFound;      // could not take it back even after reconfiguring
        return (m_ifaceBusy || m_inWake) ? kIOReturnExclusiveAccess : kIOReturnNotFound;
    }

    if (!findInterruptInPipe()) {
        IOLog(DRV ": interrupt-IN endpoint not found\n");
        closeUSB();
        return kIOReturnNotFound;
    }

    // Work loop + command gate for bounded async interrupt reads.
    if (!m_workLoop) {
        m_workLoop = IOWorkLoop::workLoop();
        if (!m_workLoop) {
            closeUSB();
            return kIOReturnNoMemory;
        }
    }
    m_cmdGate = IOCommandGate::commandGate(this);
    if (!m_cmdGate || m_workLoop->addEventSource(m_cmdGate) != kIOReturnSuccess) {
        IOLog(DRV ": command gate setup failed\n");
        closeUSB();
        return kIOReturnNoMemory;
    }

    m_evtBuf = IOBufferMemoryDescriptor::withCapacity(EVT_BUF_CAP, kIODirectionIn);
    if (!m_evtBuf || m_evtBuf->prepare() != kIOReturnSuccess) {
        IOLog(DRV ": event buffer allocation failed\n");
        closeUSB();
        return kIOReturnNoMemory;
    }
    m_evtBufPrepared = true;

    IOLog(DRV ": USB opened (interrupt-IN maxPacket=%u)\n", m_evtMaxPacket);
    return kIOReturnSuccess;
}

bool RTLBluetoothFirmware::findHCIInterface()
{
    OSIterator *iter = m_device->getChildIterator(gIOServicePlane);
    if (!iter)
        return false;

    OSObject *child;
    while ((child = iter->getNextObject())) {
        IOUSBHostInterface *iface = OSDynamicCast(IOUSBHostInterface, child);
        if (!iface)
            continue;

        const StandardUSB::InterfaceDescriptor *desc = iface->getInterfaceDescriptor();
        if (!desc)
            continue;

        // Bluetooth HCI: class 0xE0, subclass 0x01, protocol 0x01
        if (desc->bInterfaceClass == 0xE0 &&
            desc->bInterfaceSubClass == 0x01 &&
            desc->bInterfaceProtocol == 0x01)
        {
            if (iface->open(this)) {
                iface->retain();
                m_interface = iface;
            } else {
                IOLog(DRV ": HCI interface found but open failed (busy)\n");
                m_ifaceBusy = true;
            }
            break;
        }
    }
    iter->release();
    return m_interface != nullptr;
}

bool RTLBluetoothFirmware::findInterruptInPipe()
{
    const StandardUSB::ConfigurationDescriptor *cfgDesc =
        m_interface->getConfigurationDescriptor();
    const StandardUSB::InterfaceDescriptor *ifDesc =
        m_interface->getInterfaceDescriptor();
    if (!cfgDesc || !ifDesc)
        return false;

    const StandardUSB::EndpointDescriptor *ep = nullptr;
    while ((ep = StandardUSB::getNextEndpointDescriptor(cfgDesc, ifDesc,
                    reinterpret_cast<const StandardUSB::Descriptor *>(ep)))) {
        bool isIn        = (ep->bEndpointAddress & 0x80) != 0;
        bool isInterrupt = (ep->bmAttributes & 0x03) == 0x03;
        if (isIn && isInterrupt) {
            m_evtMaxPacket = OSSwapLittleToHostInt16(ep->wMaxPacketSize) & 0x07FF;
            if (m_evtMaxPacket == 0 || m_evtMaxPacket > EVT_BUF_CAP)
                m_evtMaxPacket = 16;
            m_intInPipe = m_interface->copyPipe(ep->bEndpointAddress);
            break;
        }
    }
    return m_intInPipe != nullptr;
}

void RTLBluetoothFirmware::closeUSB()
{
    if (m_intInPipe) {
        // Synchronous abort drains any pending interrupt completion (which
        // references m_cmdGate) before we tear the gate down below. closeUSB
        // never runs while holding the gate, so this cannot deadlock.
        m_intInPipe->abort(IOUSBHostIOSource::kAbortSynchronous);
        OSSafeReleaseNULL(m_intInPipe);
    }
    if (m_evtBuf) {
        if (m_evtBufPrepared) {
            m_evtBuf->complete();
            m_evtBufPrepared = false;
        }
        OSSafeReleaseNULL(m_evtBuf);
    }
    if (m_cmdGate) {
        if (m_workLoop)
            m_workLoop->removeEventSource(m_cmdGate);
        OSSafeReleaseNULL(m_cmdGate);
    }
    // Note: m_workLoop is intentionally NOT released here so it survives for PM timer
    if (m_interface) {
        m_interface->close(this);
        OSSafeReleaseNULL(m_interface);
    }
    if (m_device) {
        m_device->close(this);
        m_device = nullptr;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// HCI transport primitives
// ─────────────────────────────────────────────────────────────────────────────

IOReturn RTLBluetoothFirmware::hciCmd(uint16_t opcode,
                                      const void *params,
                                      uint8_t paramLen)
{
    // HCI command packet: [opcode LE 2B][paramLen 1B][params]
    uint8_t pkt[3 + 255];
    pkt[0] = (uint8_t)(opcode & 0xFF);
    pkt[1] = (uint8_t)(opcode >> 8);
    pkt[2] = paramLen;
    if (params && paramLen > 0)
        memcpy(pkt + 3, params, paramLen);

    StandardUSB::DeviceRequest req = {};
    req.bmRequestType = HCI_CTRL_REQ_TYPE;
    req.bRequest      = HCI_CTRL_REQ;
    req.wValue        = 0;
    req.wIndex        = 0;
    req.wLength       = (uint16_t)(3 + paramLen);

    uint32_t transferred = 0;
    return m_device->deviceRequest(this, req, pkt, transferred, HCI_CTRL_TIMEOUT_MS);
}

// Completion for the async interrupt-IN read. Runs on the USB work loop;
// records the result and wakes the (gated) caller blocked in commandSleep.
void RTLBluetoothFirmware::evtCompletion(void *owner, void *,
                                         IOReturn status,
                                         uint32_t bytesTransferred)
{
    RTLBluetoothFirmware *me = static_cast<RTLBluetoothFirmware *>(owner);
    me->m_evtStatus    = status;
    me->m_evtActualLen = bytesTransferred;
    me->m_evtInFlight  = false;
    if (me->m_cmdGate)
        me->m_cmdGate->commandWakeup(&me->m_evtInFlight);
}

// Runs holding the command gate: issue one async interrupt read and wait up
// to EVT_TIMEOUT_MS for its completion. On timeout, abort the pipe and wait
// for the (forced) completion so the buffer is never written after we return.
IOReturn RTLBluetoothFirmware::gatedEvtRead(void *, void *, void *, void *)
{
    IOUSBHostCompletion c;
    c.owner     = this;
    c.action    = &RTLBluetoothFirmware::evtCompletion;
    c.parameter = nullptr;

    m_evtStatus    = kIOReturnTimeout;
    m_evtActualLen = 0;
    m_evtInFlight  = true;

    IOReturn ret = m_intInPipe->io(m_evtBuf, m_evtMaxPacket, &c, 0);
    if (ret != kIOReturnSuccess) {
        m_evtInFlight = false;
        return ret;
    }

    uint64_t deadline = 0;
    clock_interval_to_deadline(EVT_TIMEOUT_MS, kMillisecondScale, &deadline);
    m_cmdGate->commandSleep(&m_evtInFlight, deadline, THREAD_ABORTSAFE);

    if (m_evtInFlight) {
        // Timed out (or signalled) before the read completed. Abort the pipe
        // asynchronously and wait for the forced completion to land.
        m_intInPipe->abort(IOUSBHostIOSource::kAbortAsynchronous);
        while (m_evtInFlight)
            m_cmdGate->commandSleep(&m_evtInFlight, THREAD_UNINT);
        return kIOReturnTimeout;
    }

    return m_evtStatus;
}

IOReturn RTLBluetoothFirmware::hciEvt(uint8_t *buf,
                                      uint32_t bufCap,
                                      uint32_t *outLen)
{
    if (!m_intInPipe || !m_evtBuf || !m_cmdGate)
        return kIOReturnNotOpen;

    IOReturn ret = m_cmdGate->runAction(
        OSMemberFunctionCast(IOCommandGate::Action, this,
                             &RTLBluetoothFirmware::gatedEvtRead),
        nullptr, nullptr, nullptr, nullptr);
    if (ret != kIOReturnSuccess)
        return ret;

    if (m_evtActualLen == 0)
        return kIOReturnUnderrun;

    uint32_t n = (m_evtActualLen < bufCap) ? m_evtActualLen : bufCap;
    memcpy(buf, m_evtBuf->getBytesNoCopy(), n);
    *outLen = n;
    return kIOReturnSuccess;
}

IOReturn RTLBluetoothFirmware::hciCmdSync(uint16_t opcode,
                                          const void *params, uint8_t paramLen,
                                          uint8_t *evtBuf, uint32_t evtCap,
                                          uint32_t *evtLen)
{
    IOReturn ret = hciCmd(opcode, params, paramLen);
    if (ret != kIOReturnSuccess)
        return ret;

    // Poll for the matching command-complete event, skipping unrelated events.
    for (int attempt = 0; attempt < EVT_MAX_ATTEMPTS; attempt++) {
        uint32_t len = 0;
        ret = hciEvt(evtBuf, evtCap, &len);
        if (ret != kIOReturnSuccess)
            return ret;

        if (len < 3)
            continue;

        // Command Status (0x0F): [0]=0x0F [1]=plen [2]=status [3]=numCmds [4..5]=opcode
        if (evtBuf[0] == HCI_EVT_COMMAND_STATUS && len >= 6) {
            uint16_t stOpcode = (uint16_t)(evtBuf[4] | (evtBuf[5] << 8));
            if (stOpcode == opcode) {
                if (evtBuf[2] != 0x00) {
                    IOLog(DRV ": opcode 0x%04X command-status 0x%02X\n",
                          opcode, evtBuf[2]);
                    return kIOReturnIOError;
                }
                // status 0 here means "in progress"; keep waiting for complete
            }
            continue;
        }

        // Command Complete (0x0E): [0]=0x0E [1]=plen [2]=numCmds [3..4]=opcode [5]=status
        if (evtBuf[0] != HCI_EVT_COMMAND_COMPLETE || len < 6)
            continue;

        uint16_t rspOpcode = (uint16_t)(evtBuf[3] | (evtBuf[4] << 8));
        if (rspOpcode != opcode)
            continue;

        if (evtBuf[5] != 0x00) {
            IOLog(DRV ": opcode 0x%04X completed with status 0x%02X\n",
                  opcode, evtBuf[5]);
            return kIOReturnIOError;
        }
        *evtLen = len;
        return kIOReturnSuccess;
    }
    return kIOReturnTimeout;
}

// ─────────────────────────────────────────────────────────────────────────────
// Realtek protocol (mirrors btrtl.c)
// ─────────────────────────────────────────────────────────────────────────────

IOReturn RTLBluetoothFirmware::readLocalVersion(RtlLocalVersion *out)
{
    uint8_t  evt[EVT_BUF_CAP] = {};
    uint32_t len = 0;

    IOReturn ret = hciCmdSync(HCI_OP_READ_LOCAL_VERSION, nullptr, 0,
                              evt, sizeof(evt), &len);
    if (ret != kIOReturnSuccess)
        return ret;

    // params after status: hciVer[6] hciRev[7..8] lmpVer[9] manuf[10..11] lmpSubver[12..13]
    if (len < 14)
        return kIOReturnUnderrun;

    out->hciVer       = evt[6];
    out->hciRev       = (uint16_t)(evt[7]  | (evt[8]  << 8));
    out->lmpVer       = evt[9];
    out->manufacturer = (uint16_t)(evt[10] | (evt[11] << 8));
    out->lmpSubver    = (uint16_t)(evt[12] | (evt[13] << 8));
    return kIOReturnSuccess;
}

IOReturn RTLBluetoothFirmware::rtlReadRomVersion(uint8_t *outVersion)
{
    uint8_t  evt[EVT_BUF_CAP] = {};
    uint32_t len = 0;

    IOReturn ret = hciCmdSync(RTL_OP_READ_ROM_VERSION, nullptr, 0,
                              evt, sizeof(evt), &len);
    if (ret != kIOReturnSuccess)
        return ret;

    // params after status: version[6]
    if (len < 7)
        return kIOReturnUnderrun;

    *outVersion = evt[6];
    return kIOReturnSuccess;
}

/*
 * Build the download image from the embedded rtl8761bu_fw.bin:
 * validate the "Realtech" epatch container, find the patch whose chip id
 * equals rom_version + 1, copy it, write the fw version into its last
 * 4 bytes, and append rtl8761bu_config.bin.
 * Mirrors rtlbt_parse_firmware() + btrtl_setup_rtl8723b() in btrtl.c.
 */
IOReturn RTLBluetoothFirmware::buildDownloadImage(uint8_t romVersion,
                                                  uint8_t **outBuf,
                                                  uint32_t *outLen)
{
    static const uint8_t extensionSig[RTL_EXT_SIG_LEN] = { 0x51, 0x04, 0xFD, 0x77 };

    const uint8_t  *fw    = nullptr;
    uint32_t        fwLen = 0;
    const uint8_t  *cfg   = nullptr;
    uint32_t        cfgLen = 0;

    if (m_chipVariant == ChipVariant::RTL8761B) {
        fw    = kRtl8761bFw;
        fwLen = kRtl8761bFwLen;
        cfg   = kRtl8761bConfig;
        cfgLen = kRtl8761bConfigLen;
    } else {
        fw    = kRtl8761buFw;
        fwLen = kRtl8761buFwLen;
        cfg   = kRtl8761buConfig;
        cfgLen = kRtl8761buConfigLen;
    }

    if (fwLen < RTL_EPATCH_HEADER_LEN + RTL_EXT_SIG_LEN + 3)
        return kIOReturnBadArgument;

    if (memcmp(fw, "Realtech", 8) != 0) {
        IOLog(DRV ": bad epatch signature\n");
        return kIOReturnBadArgument;
    }
    if (memcmp(fw + fwLen - RTL_EXT_SIG_LEN, extensionSig, RTL_EXT_SIG_LEN) != 0) {
        IOLog(DRV ": extension section signature mismatch\n");
        return kIOReturnBadArgument;
    }

    // Walk the extension section backwards to find the project id record.
    int projectId = -1;
    const uint8_t *p = fw + fwLen - RTL_EXT_SIG_LEN;
    while (p >= fw + RTL_EPATCH_HEADER_LEN + 3) {
        uint8_t opcode = *--p;
        uint8_t length = *--p;
        uint8_t data   = *--p;

        if (opcode == 0xFF)             // EOF
            break;
        if (length == 0) {
            IOLog(DRV ": zero-length instruction in extension section\n");
            return kIOReturnBadArgument;
        }
        if (opcode == 0x00 && length == 1) {
            projectId = data;
            break;
        }
        if (length > (uint8_t)(p - fw))  // would underflow below header
            return kIOReturnBadArgument;
        p -= length;
    }

    if (projectId != RTL8761B_PROJECT_ID) {
        IOLog(DRV ": firmware project id %d, expected %d (8761B)\n",
              projectId, RTL8761B_PROJECT_ID);
        return kIOReturnBadArgument;
    }

    uint32_t fwVersion  = OSReadLittleInt32(fw, 8);
    uint16_t numPatches = OSReadLittleInt16(fw, 12);

    // Match btrtl.c bound exactly: header + extension_sig + 3 + 8*num_patches
    if (fwLen < (uint32_t)(RTL_EPATCH_HEADER_LEN + RTL_EXT_SIG_LEN + 3) + 8u * numPatches)
        return kIOReturnBadArgument;

    // Patch tables: ChipID[n] (le16), PatchLength[n] (le16), PatchOffset[n] (le32)
    const uint32_t chipIdBase = RTL_EPATCH_HEADER_LEN;
    const uint32_t lenBase    = chipIdBase + 2u * numPatches;
    const uint32_t offBase    = lenBase    + 2u * numPatches;

    uint16_t patchLen = 0;
    uint32_t patchOff = 0;
    for (uint16_t i = 0; i < numPatches; i++) {
        if (OSReadLittleInt16(fw, chipIdBase + 2u * i) == (uint16_t)(romVersion + 1)) {
            patchLen = OSReadLittleInt16(fw, lenBase + 2u * i);
            patchOff = OSReadLittleInt32(fw, offBase + 4u * i);
            break;
        }
    }

    if (patchOff == 0 || patchLen < 4 ||
        (uint64_t)patchOff + patchLen > fwLen) {
        IOLog(DRV ": no patch for chip id %u (rom_version 0x%02X)\n",
              romVersion + 1, romVersion);
        return kIOReturnBadArgument;
    }

    IOLog(DRV ": patch fw_version=0x%08X len=%u offset=0x%X\n",
          fwVersion, patchLen, patchOff);

    uint32_t total = (uint32_t)patchLen + cfgLen;
    uint8_t *buf = (uint8_t *)IOMalloc(total);
    if (!buf)
        return kIOReturnNoMemory;

    memcpy(buf, fw + patchOff, patchLen - 4);
    OSWriteLittleInt32(buf, patchLen - 4, fwVersion);
    if (cfgLen > 0)
        memcpy(buf + patchLen, cfg, cfgLen);

    *outBuf = buf;
    *outLen = total;
    return kIOReturnSuccess;
}

IOReturn RTLBluetoothFirmware::rtlDownload(const uint8_t *data, uint32_t len)
{
    // Mirrors rtl_download_firmware(): fragment count includes a final
    // (possibly empty) fragment carrying the 0x80 end-marker index.
    uint32_t fragNum  = len / RTL_FRAG_LEN + 1;
    uint32_t fragLen  = RTL_FRAG_LEN;
    uint8_t  j        = 0;
    uint8_t  cmd[1 + RTL_FRAG_LEN];
    uint8_t  evt[EVT_BUF_CAP];

    IOLog(DRV ": downloading %u bytes in %u fragments\n", len, fragNum);

    for (uint32_t i = 0; i < fragNum; i++) {
        uint8_t index = j++;
        if (index == 0x7F)      // index wraps to 1, not 0 (btrtl.c)
            j = 1;

        if (i == fragNum - 1) {
            index |= 0x80;      // data end marker
            fragLen = len % RTL_FRAG_LEN;
        }

        cmd[0] = index;
        if (fragLen > 0)
            memcpy(cmd + 1, data + (uint64_t)i * RTL_FRAG_LEN, fragLen);

        uint32_t evtLen = 0;
        IOReturn ret = hciCmdSync(RTL_OP_DOWNLOAD_FW, cmd,
                                  (uint8_t)(fragLen + 1),
                                  evt, sizeof(evt), &evtLen);
        if (ret != kIOReturnSuccess) {
            IOLog(DRV ": fragment %u/%u failed: 0x%08X\n", i + 1, fragNum, ret);
            return ret;
        }
        // Download ack carries (status, index): event total ≥ 7 bytes.
        if (evtLen < 7) {
            IOLog(DRV ": fragment %u/%u short ack (%u bytes)\n",
                  i + 1, fragNum, evtLen);
            return kIOReturnUnderrun;
        }

        if ((i % 32) == 0)
            IOLog(DRV ": progress %u/%u fragments\n", i + 1, fragNum);
    }

    IOLog(DRV ": download complete\n");
    return kIOReturnSuccess;
}
